<?php

namespace App\Filament\Resources\ShootingSessions\Pages;

use App\Filament\Resources\ShootingSessions\ShootingSessionResource;
use Filament\Actions\EditAction;
use Filament\Resources\Pages\ViewRecord;

class ViewShootingSession extends ViewRecord
{
    protected static string $resource = ShootingSessionResource::class;

    protected function getHeaderActions(): array
    {
        return [
            EditAction::make(),
        ];
    }

    public function getContentTabLabel(): ?string
    {
        return 'Details'; // TODO: Change the autogenerated stub
    }

    public function hasCombinedRelationManagerTabsWithContent(): bool
    {
        return true;
    }
}
